# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created',
        ),
        migrations.RemoveField(
            model_name='url',
            name='created_by',
        ),
    ]
