# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20160418_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
    ]
