# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import glims.attachments_config


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=glims.attachments_config.attachment_upload_to),
        ),
    ]
