# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_auto_20160830_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='url',
            name='text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
